---
title: "Taiki's Portfolio for Computational Musicology 2023"
author: "Taiki Papandreou"
date: "2023"
output: 
  flexdashboard::flex_dashboard:
  storyboard: true
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(spotifyr)
library(ggplot2)
library(plotly)
library(compmus)
```

# Beginning of the story {.storyboard}

### Welcome to my portfolio!

In this portfolio you will find out who is more romantic Korean or Japanese?

```{r, include=FALSE}
# Loading spotify playlists
leo_playlist <- get_playlist_audio_features("", "5ASx85eUYUG7QmYpiJVI4p")
japan_playlist <- get_playlist_audio_features("", "2O5JW5bl2P4JVZxImRUOG3")
korea_playlist <- get_playlist_audio_features("", "25LukUx2r4J5WScqkEcgCo")

# Rename the playlists for my convinience
leo_playlist$playlist_name <- "Leo's playlist" 
japan_playlist$playlist_name <- "Japanese love songs"
korea_playlist$playlist_name <- "Korean love songs"

# appending datasets into one
temp = rbind(leo_playlist, japan_playlist)
songs = rbind(temp, korea_playlist)
# shows the dimension of the whole dataset
# dim(songs) # output: 247x61

wood <-
  get_tidy_audio_analysis("6ISfsK0fMMSx6mQ8TbnKhM") |>
  select(segments) |>
  unnest(segments) |>
  select(start, duration, pitches)
```

```{r}
wood |>
  mutate(pitches = map(pitches, compmus_normalise, "euclidean")) |>
  compmus_gather_chroma() |> 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c()
```

### Chart B

```{r}
# Let's see the distribution of the duration of songs in each playlist
songs <- songs %>%
  mutate(track.duration_min = track.duration_ms / (1000 * 60))
ggplot(songs, aes(track.duration_min)) + geom_histogram() + facet_wrap(~ playlist_name) + ggtitle("The distribution of song length in minutes") + labs( x = "Minutes")
```

### Chart C

```{r}
# let's make donut charts of key_mode
library(data.table)
donut_df <- songs |> count(playlist_name, key_name, sort = TRUE)

#setDT converts to a data.table and then you calculate the fraction of each expr
#grouping by the playlist_name
setDT(donut_df)[, frac := n / sum(n), by=playlist_name]
tabulated <- donut_df[, .N, by = .(playlist_name, key_name, n)]

# plot
ggplot(tabulated, aes(x=2, y=n, fill=key_name)) +
  geom_bar(position = 'fill', stat = 'identity')  +
  facet_grid(~ playlist_name) + 
  xlim(0.5, 2.5) +
  coord_polar(theta = 'y') + 
  labs(x=NULL, y=NULL) + theme(
    axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),
    axis.title.y=element_blank(),
    axis.text.y=element_blank(),
    axis.ticks.y=element_blank()
    ) + ggtitle("Distribution of keys in playlist represented in donut chart")
```

### Chart D

```{r}
ggplot(donut_df, aes(x=key_name, y=n, fill=key_name)) +
  geom_bar(stat="identity")+facet_grid(~ playlist_name) + theme(
    axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank()) + labs(y = "Count", x = "Key") + ggtitle("Distribution of keys in playlist represented in bar chart")
```
