---
title: "Taiki's Portfolio for Computational Musicology 2023"
author: "Taiki Papandreou"
date: "2023 Feb-Mar"
output: 
  flexdashboard::flex_dashboard:
  storyboard: true
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(spotifyr)
library(ggplot2)
library(plotly)
```

Page 1
==================================

Column {data-width=650}
-----------------------------------------------------------------------

### Welcome to my portfolio!
In this portfolio you will find out who is more romantic Korean or Japanese?

```{r, include=FALSE}
# Loading spotify playlists
leo_playlist <- get_playlist_audio_features("", "5ASx85eUYUG7QmYpiJVI4p")
japan_playlist <- get_playlist_audio_features("", "2O5JW5bl2P4JVZxImRUOG3")
korea_playlist <- get_playlist_audio_features("", "25LukUx2r4J5WScqkEcgCo")

# Rename the playlists for my convinience
leo_playlist$playlist_name <- "Leo's playlist" 
japan_playlist$playlist_name <- "Japanese love songs"
korea_playlist$playlist_name <- "Korean love songs"



```

Column {data-width=350}
-----------------------------------------------------------------------

Page 2
===========================

Column {data-width=650}
-----------------------------------

### Chart B

```{r}

```

Column {data-width=350}

### Chart C

```{r}

```

